-- Roles per environment
DEFINE ROLE ASSA_ENV_ADMIN_{{env}};
DEFINE ROLE ASSA_ENV_READER_{{env}};

-- Role hierarchy
GRANT ROLE ASSA_ENV_READER_{{env}} TO ROLE ASSA_ENV_ADMIN_{{env}};
GRANT ROLE ASSA_ENV_ADMIN_{{env}} TO ROLE ACCOUNTADMIN;

-- Admin: full access
GRANT USAGE ON DATABASE {{db}} TO ROLE ASSA_ENV_ADMIN_{{env}};
GRANT USAGE ON SCHEMA {{db}}.EXTRACT TO ROLE ASSA_ENV_ADMIN_{{env}};
GRANT USAGE ON SCHEMA {{db}}.STAGE TO ROLE ASSA_ENV_ADMIN_{{env}};
GRANT USAGE ON SCHEMA {{db}}.WAREHOUSE TO ROLE ASSA_ENV_ADMIN_{{env}};
GRANT ALL ON ALL TABLES IN SCHEMA {{db}}.EXTRACT TO ROLE ASSA_ENV_ADMIN_{{env}};
GRANT ALL ON ALL TABLES IN SCHEMA {{db}}.STAGE TO ROLE ASSA_ENV_ADMIN_{{env}};
GRANT ALL ON ALL TABLES IN SCHEMA {{db}}.WAREHOUSE TO ROLE ASSA_ENV_ADMIN_{{env}};

-- Reader: consumption layer only
GRANT USAGE ON DATABASE {{db}} TO ROLE ASSA_ENV_READER_{{env}};
GRANT USAGE ON SCHEMA {{db}}.WAREHOUSE TO ROLE ASSA_ENV_READER_{{env}};
GRANT SELECT ON ALL TABLES IN SCHEMA {{db}}.WAREHOUSE TO ROLE ASSA_ENV_READER_{{env}};